---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: odoo-db
  labels:
    name: odoo-db
  namespace: odoo
spec:
  selector:
    matchLabels:
      app: odoo-db
  serviceName: odoo-db
  replicas: 1
  template:
    metadata:
      labels:
        name: odoo-db
        app: odoo-db
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: odoo-db-init
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/lib/postgresql/data/pgdata/odoo']
      containers:
      - name: odoo-db
        image: postgres:9.4
        env:
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: POSTGRES_USER
          value: odoo
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata/odoo
        ports:
        - name: postgress
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/pgdata
          name: odoo-db-vol
      
      nodeSelector:
        beta.kubernetes.io/os: linux
  volumeClaimTemplates:
  - metadata:
      name: odoo-db-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
