---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  labels:
    name: odoo-db
  namespace: odoo
spec:
  ports:
    # the port that this service should serve on
  - port: 5432
    targetPort: 5432
  selector:
    name: odoo-db
